import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";
import MobileFooter from "@/components/MobileFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Score71 : A place to get sportify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <MobileFooter />
        </Providers>
       
      </body>
    </html>
  );
}
